# Pythonプログラミング入門

「Copy to Drive」ボタンを押すことで、ノートブックのコピーが自分のGoogle Drive上にコピーされ、実行・保存できるようになります

セルを上から順に「Shift + Enter」または「Shift + Return」で実行していくことで、結果を確認することができます

コード中のある行に「#」記号があると、その行それ以降はコメントとして扱われます

## 基本的な演算

### 四則演算(和・差・積・商)

In [1]:
1+2

3

In [2]:
4-3

1

In [3]:
3.14*2

6.28

In [5]:
5/2

2.5

割り算(/)の結果は必ず実数になります。整数の結果が欲しい場合には"//"を使います

In [6]:
4//2

2

In [7]:
5//2

2

### べき乗

aのb乗を計算したい場合には "a**b" と書きます

In [8]:
2**3

8

### 指数関数・三角関数

これらの関数を使うには、あらかじめmathモジュールをインポートしておく必要があります。mathモジュールをインポートすると、円周率(pi)などの定数も使えるようになります。モジュールのインポートは一度行えば、そのノートブックの中ではそれ以降ずっと有効となります

指数関数

In [11]:
import math
math.exp(2.0)

7.38905609893065

三角関数

In [23]:
math.cos(math.pi)

-1.0

## 変数

整数や実数の値は変数に代入することができます

In [24]:
a = 2.0
b = 1.5

In [25]:
a+b

3.5

In [26]:
math.cos(a*math.pi)

1.0

In [27]:
b=a

In [28]:
b+1

3.0

## 配列

### 一次元の配列

配列には、numpyモジュールに含まれるarrayを使います。numpyモジュールはnpという名前でインポートします

In [29]:
import numpy as np
a=np.array([1,2,3,4,5]) # 長さ5の1次元配列を作成し、aに代入

In [30]:
a

array([1, 2, 3, 4, 5])

In [20]:
a[0] # Pythonでは配列の添字は0から始まることに注意

1

In [31]:
a[4] # 最後の要素の添字は(配列の長さ-1)であることに注意

5

In [32]:
a[5] # 添字5は6番目の要素を指すのでエラーとなる

IndexError: index 5 is out of bounds for axis 0 with size 5

In [33]:
a[-1] # 負の添字は後ろから数えることを意味する。添字-1は最後の要素を指す

5

In [34]:
a[-2] # 添字-2は最後から二番目の要素

4

### 配列のスライス

In [35]:
a[1:3] # i:j と指定すると添字iからj-1までを含む部分配列を返す

array([2, 3])

In [36]:
a[:] # 数字を省略すると最初から最後までを返す

array([1, 2, 3, 4, 5])

In [37]:
a[1:-2] # 負の添字も使える。長さが5の配列の場合、a[1:-2]はa[1:3]と等価

array([2, 3])

### 配列の演算

In [38]:
3*a # 配列に定数を掛けるとそれぞれの要素が定数倍される

array([ 3,  6,  9, 12, 15])

In [40]:
b=np.array([2,3,4,5,6])
a+b # 同じ長さの配列の和を取ると、結果はそれぞれの要素の和を要素として持つ配列となる

array([ 3,  5,  7,  9, 11])

In [43]:
a[1:3]+b[0:2] # 配列のスライス同士の和も計算できる。スライスの長さは同じである必要がある

array([4, 6])

In [42]:
a[1:3]+b[0:4] # 長さが違う場合にはエラーとなる

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

## 二次元配列

In [1]:
n=10
for k in range(n):
    m=2*k
    print(m)

0
2
4
6
8
10
12
14
16
18


matplotlibモジュールを使うことで、二次元や三次元のグラフや動画を作成することができます

動画の作成方法
まず、各コマを描画する関数(update)を作成し、それをanimation.FuncAnimation関数に渡します